FROM arm32v6/alpine:3.9.4

COPY qemu-arm-static           /usr/bin/

COPY /bin/node_exporter_armv6  /bin/node_exporter
COPY conf                      /etc/node-exporter

ENV NODE_ID=none

EXPOSE     9100
USER       root
ENTRYPOINT [ "/etc/node-exporter/docker-entrypoint.sh" ]
#CMD [ "/bin/node_exporter" ]
