FROM arm64v8/alpine:3.11.5

COPY qemu-aarch64-static      /usr/bin/

COPY bin/node_exporter_arm64  /bin/node_exporter
COPY conf                     /etc/node-exporter

ENV NODE_ID=none

EXPOSE     9100
USER       root
ENTRYPOINT [ "/etc/node-exporter/docker-entrypoint.sh" ]
#CMD [ "/bin/node_exporter" ]
